Levelup
Teaching-projects/SZE-MOSZE-2020-Kumisztan--Closed pull request #3
Opened 2020-10-15 16:13 UTC by vargussen97

@oliverosz elkészültem a szintlépéses feladattal.

2020-10-19 10:02 UTC, vargussen97 commented
@oliverosz kérhetek egy review-t? 🙂

2020-10-21 21:33 UTC, oliverosz requested changes

2020-10-21 21:33 UTC, oliverosz commented on Fighters.cpp
> +            enemy.hp = 0;
Itt nem kap xp-t.

2020-10-21 21:33 UTC, oliverosz commented on Fighters.cpp
> +            int i = round(getXP()/100);
Ez kiszámolja, hány szintet kell lépnie, de a statok mindenképp csak egyszer növekednek.

2020-10-21 21:33 UTC, oliverosz commented on Fighters.cpp
> +                enemy.maxhp += enemy.maxhp*0.1;
Itt hiányzik a kerekítés.

2020-10-21 21:33 UTC, oliverosz commented on Fighters.cpp
> +            hp = 0;
Nem jár xp.

2020-10-21 21:33 UTC, oliverosz commented on main.cpp
> +   		}
Most a Fighton belül is van egy ciklus, amiben oda-vissza ütik egymást, meg itt is. Csak egy helyen szerepeljen ez a loop.

2020-10-25 09:58 UTC, vargussen97 commented
@oliverosz végeztem a hibák javításával, ha minden igaz

2020-10-25 20:02 UTC, oliverosz requested changes

2020-10-25 20:02 UTC, oliverosz commented on .vscode/settings.json
> +}
Az IDE beállítások ne jelenjenek meg a repóban.

2020-10-25 20:02 UTC, oliverosz commented on Fighters.cpp
> +        xp += getDmg();
Most meg nem annyi xp-t kap, amennyit kéne. Ha az ellenségnek kevesebb volt az élete, akkor kevesebb a bevitt sebzés és így az xp is.

2020-10-25 20:02 UTC, oliverosz commented on Fighters.cpp
> +        }
Ez nem lett kijavítva. Még mindig nem tud több szintet lépni egy ütésből, és a kerekítés se jó, a floor az nem kerekít, hanem veszi az egész részt.

2020-10-26 15:54 UTC, vargussen97 commented
@oliverosz Remélhetőleg most már kijavítottam mindent

2020-10-26 20:22 UTC, oliverosz requested changes

2020-10-26 20:22 UTC, oliverosz commented on Fighters.cpp
> +        double i = 0;
Miért lett ebből double, ha aztán úgyis egy intté castolt hányadost kap értékül?

2020-10-26 20:22 UTC, oliverosz commented on Fighters.cpp
> +        else if (enemy.getHP()-getDmg() < 0)
Kár volt idetenni ezt a feltételt. Most mi történik, ha épp annyit sebezne, mint amennyi az ellenség élete? A sebzés se történik meg, és xp-t se kap.

2020-10-26 20:22 UTC, oliverosz commented on .gitignore
> +.vscode/settings.json
az egész .vscode mappát lehet ignorálni

2020-10-26 20:22 UTC, oliverosz commented on Fighters.cpp
> +        i = (int) getXP() / 100;
Ez továbbra sincs megfelelően használva. Akármennyi az értéke, a statok vagy 0-szor vagy 1-szer növekednek csak. Még egy lehetőséget adok javításra, de ez az utolsó.

2020-10-27 17:04 UTC, vargussen97 commented
@oliverosz Elkészültem az utolsó próbálkozással, while ciklust használtam a többszöri szintlépés érdekében

2020-10-29 10:11 UTC, oliverosz reviewed
OK, a levelup feladat megoldása rendben van. Akkor most lehet frissíteni a masterre, és kijavítani a conflictokat, hogy mergelhessem a PR-t. Figyelj rá, hogy szintlépéskor az attackspeednek is gyorsulnia kell 10%-ot.

2020-11-03 12:08 UTC, vargussen97 commented
@oliverosz végeztem a conflictok feloldásával, szintlépésnél pedig 10%-ot nő az attackspeed

2020-11-03 20:45 UTC, oliverosz approved these changes

2020-11-03 20:45 UTC, merged