Jsonparser
Teaching-projects/SZE-MOSZE-2020-Kumisztan--Closed pull request #5
Opened 2020-10-16 02:12 UTC by Kumiszter

@wajzy végeztem a feladat ezen részével.

2020-10-20 18:19 UTC, wajzy requested changes
Kicsit bolondbiztosabbá kellene tenni a kódot, és ezt igazoló tesztesetekre is szükség lenne.

2020-10-20 18:19 UTC, wajzy commented on json.cpp
> +	std::string ln,ln1,ln2;
Ezek nem valami kifejező változónevek.

2020-10-20 18:19 UTC, wajzy commented on json.cpp
> +		if (ln.find('{') == std::string::npos && ln.find('}') == std::string::npos)
Ezt a feltételt itt nem nagyon értem. A JSON fájl egy sora ugyanúgy érvényes marad, ha a kulcsot a { karakter után írom közvetlenül, mintha új sorba írnám.

2020-10-20 18:19 UTC, wajzy commented on json.cpp
> +			for (unsigned int i = 0; i < ln.find(':'); i++)
Tehát minden karakter megvizsgálása után megkeresteted a : helyét? Nem lesz túl gyors... Arról nem beszélve, hogy valaki egy gépelési hiba folytán el is feledkezhet erről a jelről, és az ilyen hibákra jó lenne készülni.

2020-10-20 18:19 UTC, wajzy commented on json.cpp
> +std::map<std::string, std::string> Parser::Parse_string(std::string fileName)
Kicsit félrevezető a fv. neve.

2020-11-04 02:33 UTC, Kumiszter commented
@wajzy Ha minden igaz sikerült kiküszöbölni a problémákat talán.

2020-11-04 09:48 UTC, wajzy approved these changes
Szerintem ez így még mindig nem OK, de tekintve arra, hogy a következő feladatok amúgy is a parzer jelentős továbbfejlesztését igénylik, ezt most továbbengedem.

2020-11-04 09:48 UTC, wajzy commented on json.cpp
> +	std::string line,line1,line2;
A változók mechanikus átnevezése nem vezet automatikusan egy könnyebben követhető kódra. Olyan neveket kellene választani, ami utal a változó funkciójára, arra, hogy mit akarsz tárolni benne.

2020-11-04 09:48 UTC, wajzy commented on json.cpp
> +std::map<std::string, std::string> Parser::Parse_string(const std::string& input)
Most akkor van két, kísértetiesen hasonlító függvényed string parzolásra?

2020-11-04 16:13 UTC, merged